### ISSUE TITLE
Folder color block is too high

### ISSUE THREAD

**Issue by mrsnax** [oguhpereira/Dracula-cmder#2]
Hi

Please change the green color of folder make readable

![image](https://user-images.githubusercontent.com/6369589/50294158-e46e6380-04a7-11e9-9f8f-e9d7f1e49f60.png)

Its hard to read :(

**Comment by ogustavo-pereira** [comment]
Hi thank's fot the issue,

I will change it!

**Comment by ogustavo-pereira** [comment]
I changed the background color, please verify new feature!
