### ISSUE TITLE
Invisible text when using git status

### ISSUE THREAD

**Issue by JosephGaiser** [oguhpereira/Dracula-cmder#3]
`git status` Will return invisible text (the same color as the background) on added files.
This only happens to files that you have staged to be committed. Unstaged files will show in red.

Reproduce:
1. edit some files then `git status` shows files in red
2. `git add -A` 
3. `git status` added filed invisible

**Comment by MathieuMarchant** [comment]
The same issue occurs when you want to list all branches. 
The currently checked out branch is also invisibile.

`git branch -a`

**Comment by JosephGaiser** [comment]
@EagleWizard28 I just noticed this an hour ago. Thanks!

**Comment by MathieuMarchant** [comment]
Additionally while using git log, the commit ID's are not shown. So please validate the colors again with several git commands.

`git log`

**Comment by JosephGaiser** [comment]
I just conirmed that same behavior on my end as well.

**Comment by ogustavo-pereira** [comment]
Thanks for your pull request.

I will update fixing the bug

**Comment by ogustavo-pereira** [comment]
I changed some colors to fix these bugs e83081ff11fee47c06a4987dad7b6403fbb75e34
