### ISSUE TITLE
Failed to create font!

### ISSUE THREAD

**Issue by ayonsaha2011** [oguhpereira/Dracula-cmder#4]
![image](https://user-images.githubusercontent.com/11154183/64074035-7ed3a780-ccc3-11e9-8f1b-7fb927dacb08.png)

**Comment by ogustavo-pereira** [comment]
@ayonsaha2011  thanks for the issue.

I removed the default font firacodex and changed for consoles

**Comment by hhhaiai** [comment]
![image](https://user-images.githubusercontent.com/5738285/97650420-9576b980-1a94-11eb-9f3f-d480080d4627.png)
me too. 
win 10
new version

**Comment by hhhaiai** [comment]
@oguhpereira

**Comment by ogustavo-pereira** [comment]
@hhhaiai which version are you using?
