### ISSUE TITLE
Nothing happens after import

### ISSUE THREAD

**Issue by bevrard** [oguhpereira/Dracula-cmder#5]
Hello,

Nothing happens after import.  Could you tell me if I need a specific cmder version?

Kind regards

**Comment by ogustavo-pereira** [comment]
No @bevrard,  I always tested on the latest cmder version.

On the [settings page](https://conemu.github.io/en/SettingsColors.html)  you can choose the theme,look if have the dracula option

**Comment by bevrard** [comment]
I've downloaded the last one from the website.  A theme is applied but there is no dracula item in the color schemes list.

**Comment by brcmesquita** [comment]
I'm using Windows 10 (build 15063), Cmder (v. 191012). No problems here.
![image](https://user-images.githubusercontent.com/13441032/73596345-20278980-4500-11ea-9519-30c50ab95342.png)

**Comment by giovannipds** [comment]
Hi @bevrard It worked exactly as expected here, same as @brcmesquita mentioned. It's asked to merge the imports and applied the theme. The theme name appears on the dropdown list too. If you do not provide more information, perhaps we should already close this issue, is from a year ago already.

**Comment by brcmesquita** [comment]
Some software has its theme updated (changed) automatically after import, which does not happen with cmder. You need to do it yourself.

**Comment by giovannipds** [comment]
@brcmesquita When I imported it on the latest cmder it already applied the theme as well.

**Comment by ogustavo-pereira** [comment]
Currently closed
