### ISSUE TITLE
Error after import

### ISSUE THREAD

**Issue by tuanden0** [oguhpereira/Dracula-cmder#7]
After import Dracular.xml, I got this error

![problems](https://i.imgur.com/Fe1e2Yt.png)

**Comment by ogustavo-pereira** [comment]
Thank you for reporting this issue 🐛 

It was happening because in the xml there were my task settings 😅 

I changed to the default cmder settings :v:

3cedb8c7925ccfd1ae7bf68b83e91d1f3bf5d75f
